CREATE INDEX "idx_analysis_jobs_org_id" ON "analysis_jobs" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_analysis_jobs_status" ON "analysis_jobs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_analysis_jobs_subject_id" ON "analysis_jobs" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "idx_analysis_jobs_requested_by" ON "analysis_jobs" USING btree ("requested_by");--> statement-breakpoint
CREATE INDEX "idx_analysis_subjects_org_id" ON "analysis_subjects" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_actor_id" ON "audit_logs" USING btree ("actor_id");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_action" ON "audit_logs" USING btree ("action");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_org_id" ON "audit_logs" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_created_at" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_consents_org_id" ON "consents" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_consents_subject_id" ON "consents" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "idx_consents_status" ON "consents" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_form_org_assignments_form_id" ON "form_organization_assignments" USING btree ("form_id");--> statement-breakpoint
CREATE INDEX "idx_form_org_assignments_org_id" ON "form_organization_assignments" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_form_submissions_form_id" ON "form_submissions" USING btree ("form_id");--> statement-breakpoint
CREATE INDEX "idx_form_submissions_org_id" ON "form_submissions" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_form_submissions_submitted_at" ON "form_submissions" USING btree ("submitted_at");--> statement-breakpoint
CREATE INDEX "idx_form_versions_form_id" ON "form_versions" USING btree ("form_id");--> statement-breakpoint
CREATE INDEX "idx_notifications_recipient_id" ON "notifications" USING btree ("recipient_id");--> statement-breakpoint
CREATE INDEX "idx_notifications_is_read" ON "notifications" USING btree ("is_read");--> statement-breakpoint
CREATE INDEX "idx_notifications_created_at" ON "notifications" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_org_members_org_id" ON "organization_members" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_org_members_user_id" ON "organization_members" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_org_members_role" ON "organization_members" USING btree ("role");--> statement-breakpoint
CREATE INDEX "idx_org_products_product_id" ON "organization_products" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "idx_reports_org_id" ON "reports" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_reports_subject_id" ON "reports" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "idx_team_invitations_email" ON "team_invitations" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_team_invitations_status" ON "team_invitations" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_team_invitations_org_id" ON "team_invitations" USING btree ("organization_id");